export const slides = [
  {
    year: '1914',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 1,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '10s',
    },
  },
  {
    year: '1915',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 2,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '10s',
    },
  },
  {
    year: '1920',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 3,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '20s',
    },
  },
  {
    year: '1921',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 4,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '20s',
    },
  },
  {
    year: '1925',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 5,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '20s',
    },
  },
  {
    year: '1927',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 6,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '20s',
    },
  },
  {
    year: '1939',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 7,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '30s',
    },
  },
  {
    year: '1942',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 8,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '40s',
    },
  },
  {
    year: '1943',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 9,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '40s',
    },
  },
  {
    year: '1944',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 10,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '40s',
    },
  },
  {
    year: '1953',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 11,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '50s',
    },
  },
  {
    year: '1954',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 12,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '50s',
    },
  },
  {
    year: '1955',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 13,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '50s',
    },
  },
  {
    year: '1963',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 14,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '60s',
    },
  },
  {
    year: '1965',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 15,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '60s',
    },
  },
  {
    year: '1972',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 16,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '70s',
    },
  },
  {
    year: '1974',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 17,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '70s',
    },
  },
  {
    year: '1978',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 18,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '70s',
    },
  },
  {
    year: '1979',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 19,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '70s',
    },
  },
  {
    year: '1979.2',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 20,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '70s',
    },
  },
  {
    year: '1980',
    category: 'Brasileiro',
    star: true,
    superStar: true,
    slideNumber: 21,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '80s',
    },
  },
  {
    year: '1981',
    category: 'Libertadores',
    star: true,
    superStar: true,
    slideNumber: 22,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '80s',
    },
  },
  {
    year: '1981',
    category: 'Mundial',
    star: true,
    superStar: true,
    slideNumber: 23,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '80s',
    },
  },
  {
    year: '1981',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 24,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '80s',
    },
  },
  {
    year: '1982',
    category: 'Brasileiro',
    star: true,
    superStar: true,
    slideNumber: 25,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '80s',
    },
  },
  {
    year: '1983',
    category: 'Brasileiro',
    star: true,
    superStar: true,
    slideNumber: 26,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '80s',
    },
  },
  {
    year: '1986',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 27,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '80s',
    },
  },
  {
    year: '1990',
    category: 'CopaDoBrasil',
    star: true,
    superStar: false,
    slideNumber: 28,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '90s',
    },
  },
  {
    year: '1991',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 29,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '90s',
    },
  },
  {
    year: '1992',
    category: 'Brasileiro',
    star: true,
    superStar: true,
    slideNumber: 30,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '90s',
    },
  },
  {
    year: '1996',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 31,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '90s',
    },
  },
  {
    year: '1999',
    category: 'Mercosul',
    star: false,
    superStar: false,
    slideNumber: 32,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '90s',
    },
  },
  {
    year: '1999',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 33,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '90s',
    },
  },
  {
    year: '2000',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 34,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '00s',
    },
  },
  {
    year: '2001',
    category: 'Carioca',
    star: true,
    superStar: true,
    slideNumber: 35,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '00s',
    },
  },
  {
    year: '2004',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 36,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '00s',
    },
  },
  {
    year: '2006',
    category: 'CopaDoBrasil',
    star: true,
    superStar: false,
    slideNumber: 37,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '00s',
    },
  },
  {
    year: '2007',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 38,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '00s',
    },
  },
  {
    year: '2008',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 39,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '00s',
    },
  },
  {
    year: '2009',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 40,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '00s',
    },
  },
  {
    year: '2009',
    category: 'Brasileiro',
    star: true,
    superStar: true,
    slideNumber: 41,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '00s',
    },
  },
  {
    year: '2011',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 42,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '10s',
    },
  },
  {
    year: '2013',
    category: 'CopaDoBrasil',
    star: true,
    superStar: false,
    slideNumber: 43,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '10s',
    },
  },
  {
    year: '2014',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 44,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '10s',
    },
  },
  {
    year: '2017',
    category: 'Carioca',
    star: false,
    superStar: false,
    slideNumber: 45,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '10s',
    },
  },
  {
    year: '2019',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 46,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '10s',
    },
  },
  {
    year: '2019',
    category: 'Brasileiro',
    star: true,
    superStar: true,
    slideNumber: 47,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '10s',
    },
  },
  {
    year: '2019',
    category: 'Libertadores',
    star: true,
    superStar: true,
    slideNumber: 48,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '10s',
    },
  },
  {
    year: '2020',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 49,
    hasLink: false,
    firstOfDecade: {
      first: true,
      decade: '20s',
    },
  },
  {
    year: '2020',
    category: 'Brasileiro',
    star: true,
    superStar: true,
    slideNumber: 50,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '20s',
    },
  },
  {
    year: '2021',
    category: 'Carioca',
    star: true,
    superStar: false,
    slideNumber: 51,
    hasLink: false,
    firstOfDecade: {
      first: false,
      decade: '20s',
    },
  },
  {
    year: '2022',
    category: 'CopaDoBrasil',
    star: true,
    superStar: false,
    slideNumber: 52,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '20s',
    },
  },
  {
    year: '2022',
    category: 'Libertadores',
    star: true,
    superStar: true,
    slideNumber: 53,
    hasLink: true,
    firstOfDecade: {
      first: false,
      decade: '20s',
    },
  },
]
